### PR TITLE
Loan Conditions and Loan Exceptions (without finalized GUI)

### PR DESCRIPTION
**Pull request by jongravois**
The GUI on the underwriting tab needs work and the exception formulas need to be checked.

### CODE REVIEW

**Comment by petrovitch** [comment]
How do I enable the pull list? When I click on the site that shows me the
changes the merge pull list button is disabled.

**Comment by petrovitch** [comment]
I see "Lock pull request" in the right column.  Do you have it locked?

**Comment by jongravois** [comment]
Looks like the auto-merge isn't available for this Request. I'm pretty sure it is because I rolled back my local repo from your Pull Request because we were getting those errors and I manually added your changes to my repo. But since my repo is one behind this one, the auto merge isn't available.

If says "we can't automatically merge this pull request. use the command line to resolve conflicts." I'll have to research that.

**Comment by jongravois** [comment]
not locked

**Pull request merged**
